stages:
    - build

docker-build-master:
  # Official docker image.
  image: docker:18.09.7
  stage: build
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:18.09.7-dind
      command: ["--experimental"]    # Enable experimental features in Docker server
  # before_script:
    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - DOCKER_BUILDKIT=1 DOCKER_CLI_EXPERIMENTAL=enabled docker version
    # - ./build.sh
    - DOCKER_BUILDKIT=1 DOCKER_CLI_EXPERIMENTAL=enabled docker build .
    # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    # - docker push "$CI_REGISTRY_IMAGE"

